pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git 'https://github.com/Vish0999/aws-data-pipelines.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    sh '''
                    docker build -t data-pipeline-app ./docker
                    '''
                }
            }
        }
        stage('Push to ECR') {
            steps {
                script {
                    sh '''
                    aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 851725602161.dkr.ecr.eu-north-1.amazonaws.com
                    docker build -t myrepo .
                    docker tag myrepo:latest 851725602161.dkr.ecr.eu-north-1.amazonaws.com/myrepo:latest
                    docker push 851725602161.dkr.ecr.eu-north-1.amazonaws.com/myrepo:latest
                    '''
                }
            }
        }
        stage('Deploy Infrastructure') {
            steps {
                script {
                    dir('terraform') {
                        sh 'terraform init'
                        sh 'terraform apply -auto-approve'
                    }
                }
            }
        }
    }
}
